#
# DES: Sealed secret 
# URL: https://github.com/bitnami-labs/sealed-secrets
#
# HELM-REF:
#  https://github.com/democratic-csi/charts/blob/b08d58f079d3ac812a75454c4d992f10c830af04/stable/democratic-csi/templates/driver-config-secret.yaml#L1
#  https://github.com/democratic-csi/charts/blob/b08d58f079d3ac812a75454c4d992f10c830af04/stable/democratic-csi/templates/controller.yaml#L40
#
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: democratic-driver-config-iscsi
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgDQk34KqUBhiRJb+Vw7IhVS+2LD6jp3HqBMBAOKCdiQisFGuy0iqgOCXpcmP3cPa7jttZhebbCaGr02Bo9aohJKLuqvBQrwoQm2gPk1JpQJj2oLCzThE+cG11/ZIZpkfvj0JDHTpVhE8F4/fWq6stDiYMByZkwF0B8Uz7SHQntffr0H/8yyWGm83udAC64Ei6wXhtxE7uFYC0cok+RpE0QRobOGaMSY+OleIXJrYC7Lij2nXNuCUzkmqMxIjM8BvvQgN5Lv5iqgSDyFwWsvqthk8y/0fqjdaor5lMFUV04swFhwcA8dLV2wYH0gLKf1XXrygoT3m0o/fRTz6qW/JfUO4eHUtkSiXKjrGxG8V6g/sPnPkbAM2fQlYAHyI9xc5r24hP6sBdP48CyiRnn/VPHa7GuJf5EorwuofIMjfoUQGXRgohN20Bm0e8vK4A1ymcwY2b4JZAshhETFiyAWGIsT/YkolNDE5jOwq7ChbFj0jgfVFRiRB1K1ykQaIFXyo1R/dDXLjtWRyiPcKT8SN6V/gaU8ad6ao4mp9uEiH7C5asMYSuQwcu+o8t5dl0KKFcda/K8oxu5CYRDvjwmshdrEAvtcwdSerWJim1Y4dmAxO1weVcBqqcBA3LNqsxNYUlSMPdOt4v4u4ua8J+I+37nubIj59zpyLA4AoGi1q3ffRkoyyU/2vD6MUxxiDNMd7GhOrBcu5YPddYq+lEkN6E/SGL2ix8dMunOQgpVazPSxVay8SWfdE2rlWZLhrlGL8/zQ4jGWSVxuGRdnrshTC4/gQ2yJZ3sY5GLdvdk1lvmLq0H0wDw62hgdxNYmJtzQmVaT45kpPRdbyJGf8PaHZeqfW7ot9vL9Lt7yTCmh1tf2XwTuh8xU9nAzjc1WQId+azzhJojbpzPgH8awHbiDEo6ZGXUvR96bZO+QKtugfhTuyEUI58cIU2V4ySX3pVDHn6yEPl1PZIBv/j/C/R9wRxmUgsL04jTOiGvZ796RxAZK1WmenVrkwVnsFAyvY0R7Gx6NHAUxG4Wcv5GAkIqb9iDDP2qjTHaeRvr96P4Tnk7VwWX7XR4pZofEkH72crvaf4DLh/HdTD5ftvkqI6VgWJtRRqeNDNDusvngGaXZ2rgc0N3bNADEowv3/BD8aRrHZJ5y1I0rQdLgvm2ffevaDCyYPgf0dYnofbzTc1+gyLvIDzVvlNzFv9QUyzKjIae6fKUlBnmAMZt1o0Wm0ZvSvGsVqe+0Q6ffjQfjWixiSebwNVHHultAoqPL/nKTsSVLSX3HffxDJvDDhCXQRH7K8vHpDBI0pIpgLTcv/6lYVVaDahmcZxc63i1T3Vm16MB1ZlpM8qswtKDXeLtWEPhS6toA9a7llz0vPdVWgoyk4BlLJO6oP/nRg8DDKP5RoO55FSWpHzp3gbKnSCA8reDL/4dvar5/A3uiuxAA/hi3y/uW95RFzeHkGDg83mrIolUZ8MA5B2eIVJE//e0goXxpZv+bsJ58bn5fHQimXfHL91w/lVLcEkw2v80vnr6yChTLHyQhBrtm7zpjz9OVtRv1lNmgpdh/DdG9f2ugIUAdzWCUBykrPNjUGvgsGZXc6GhDZUgSBQwIunMGxqt0kg50CYYvOEJ4V39MZk8uf3lW6ZxlXMZ5Dmccu0VeyqdvjdHnnPkXp9RhddCZTGGXHvba46cEgIpItfHyOpUtY0vmI4YyBLDEq3ZXqR9y2eiiamISWT4IjAtdO1iG9TJxES0nkz/d8Mp0cTKzg2/dyWCT
  template:
    metadata:
      creationTimestamp: null
      name: democratic-driver-config-iscsi
      namespace: democratic-csi
    type: Opaque
...
