#
# DES: ArgoCD apps of apps
# URL: 
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/utilizable/charts'
      targetRevision: HEAD
      path: applications/democratic-csi/argocd
    - repoURL: 'https://github.com/utilizable/charts'
      targetRevision: HEAD
      path: applications/sealed-secrets/argocd
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
