#
# DES: ArgoCD apps of apps
# URL: 
#
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test 
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/utilizable/charts
        revision: HEAD
        files:
          - path: ./applications/applications.yml
  template:
    metadata:
      name: application
    spec:
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- range .applications }}
      {{- if .enable }}
       metadata:
        name: {{ .name }} 
      spec:
        source:
             repoUrl: 'https://github.com/utilizable/charts'
             targetRevision: 'HEAD'
             path: ./applications/{{ .name }}/argocd
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: 'argocd'
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
      {{- end }}
    {{- end }}
...
