apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationset
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    path: democratic-csi/argocd
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
