apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications 
  namespace: argocd
spec:
  project: default 
  sources:
    - repoURL: 'https://github.com/utilizable/charts'
      targetRevision: HEAD
      path: ./generators/
        #releaseName: infrastructure 
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
