applications:

    - name: sealed-secrets
      enable: true
      
    - name: democratic-csi-nfs
      enable: false
      
    - name: democratic-csi-iscsi
      enable: false
      
    - name: nvidia-device-plugin
      enable: true
      
    - name: local-path-provisioner
      enable: true
      
    - name: traefik
      enable: true
