applications:

    - name: sealed-secrets
      #chartName:
      #chartPath:
      chartValues: true
      targetRevision: 2.16.1
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      manifests: true
      #namespace: 
      
    - name: nvidia-device-plugin
      #chartName:
      #chartPath: 
      chartValues: true
      targetRevision: 0.16.0
      repoURL: https://nvidia.github.io/k8s-device-plugin
      manifests: true     
      #namespace: 

    - name: local-path-provisioner
      #chartName:
      #chartPath: 
      targetRevision: v0.0.28 
      repoURL: https://github.com/rancher/local-path-provisioner
      chartPath: ./deploy/chart/local-path-provisioner
      #namespace: 
      
#    - name: democratic-csi-nfs
#      targetRevision:
#      repoURL:
      
#    - name: democratic-csi-iscsi
#      targetRevision:
#      repoURL:
      
#    - name: nvidia-device-plugin
#      targetRevision: 0.16.0
#      repoURL: https://nvidia.github.io/k8s-device-plugin
#      helmValues: true
#      k8sManifests: true
      
#    - name: local-path-provisioner
#      targetRevision: v0.0.28 
#      repoURL: https://github.com/rancher/local-path-provisioner
#      path: ./deploy/chart/local-path-provisioner
      
#    - name: traefik
#      targetRevision: 30.0.2
#      repoURL: https://traefik.github.io/charts
#      helmValues: true
#      k8sManifests: true
