#
# DES: ArgoCD application definition for sealed-secrets
# REF: https://github.com/bitnami-labs/sealed-secrets
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik 
  namespace: argocd
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
  - repoURL: 'https://traefik.github.io/charts'
    targetRevision: 30.0.2
    chart: traefik
    helm:
      valueFiles:
        - $values/applications/sealed-secrets/helm/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
