#
# DES: ArgoCD application definition for democratic-csi application
# REF: 
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-nfs
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    path: applications/democratic-csi/manifests/
  - repoURL: 'https://democratic-csi.github.io/charts/'
    chart: democratic-csi
    targetRevision: 0.14.6
    helm:
      values: |
        fullnameOverride: democratic-csi-nfs
        driver:
          existingConfigSecret: democratic-driver-config-nfs
      valueFiles:
        - $values/applications/democratic-csi/helm/values-nfs.yaml
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-iscsi
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    path: applications/democratic-csi/manifests/
  - repoURL: 'https://democratic-csi.github.io/charts/'
    chart: democratic-csi
    targetRevision: 0.14.6
    helm:
      values: |
        fullnameOverride: democratic-csi-iscsi
        driver:
          existingConfigSecret: democratic-driver-config-iscsi
      valueFiles:
        - $values/applications/democratic-csi/helm/values-iscsi.yaml
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
