#
# DES: ArgoCD application definition for democratic-csi application
# REF: 
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    path: applications/democratic-csi/manifests/
    syncPolicy:
      automated:
        prune: false
  - repoURL: 'https://democratic-csi.github.io/charts/'
    chart: democratic-csi
    targetRevision: 0.14.6
    helm:
      valueFiles:
        - $values/applications/democratic-csi/helm/values.yaml
    syncPolicy:
      automated:
        prune: false
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    ref: values
    syncPolicy:
      automated:
        prune: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
