#
# DES: ArgoCD application definition for sealed-secrets
# REF: https://github.com/bitnami-labs/sealed-secrets
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: infrastructure
  sources:
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    path: sealed-secrets/manifests/
  - repoURL: 'https://bitnami-labs.github.io/sealed-secrets/'
    chart: sealed-secrets-controller
    targetRevision: 1.16.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
