{{- range .Values.applications -}}
{{ if not .disable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: 'default' 
  source:
    repoURL:  {{ .repoURL }}
    targetRevision: {{ .targetRevision }}

    {{- if hasKey . "chartPath" }}
    path: {{ .chartPath }}
    {{- end -}}

    {{- if hasKey . "chartName" }}
    chart: {{ .chartName }} 
    {{- end -}}
    
    {{- if not (or (hasKey . "chartPath") (hasKey . "chartName")) }}
    chart: {{ .name }}
    {{- end }}    

    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
---
{{- end }}
{{- end }}
