---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'generator'
  namespace: 'argocd'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
         - git:
             repoURL: 'https://github.com/utilizable/charts'
             revision: HEAD 
             files:
               - path: 'sets/infrastructure.yml'
         - list:
             elementsYaml: '{{ `{{ .applications | toYaml }}` }}'
  template:
    metadata:
      name: test
    spec:
      project: default 
      sources:
        - repoURL: https://github.com/argoproj/argocd-example-apps.git
          targetRevision: HEAD
          path: guestbook
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'default'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

...
