---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'generator'
  namespace: 'argocd'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
         - git:
             repoURL: 'https://github.com/utilizable/charts'
             revision: HEAD 
             files:
               - path: {{ $.Values.file }}
         - list:
             elementsYaml: '{{ `{{ .applications | toYaml }}` }}'
  template:
    metadata:
      name: test-app
    spec:
      project: default 
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'default'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatepatch: |
    spec:
      sources:
        - repoUrl: "testdd" 
          targetRevision: "testdd"
          path: "testdd"
...
