---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'generator'
  namespace: 'argocd'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
         - git:
             repoURL: 'https://github.com/utilizable/charts'
             revision: HEAD 
             files:
               - path: {{ $.Values.file }}
         - list:
             elementsYaml: '{{ `{{ .applications | toYaml }}` }}'
  template:
    metadata:
      name: test-app
    spec:
      project: default 
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'default'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatepatch: |
    metadata:
      annotations:
        '{{ `{{- if haskey . "priority" }}` }}'
        argocd.argoproj.io/sync-wave: "'{{ `{{ .priority }}` }}'"
        '{{ `{{- end }}` }}'
    spec:
      destination:
        {{- if haskey . "namespace" }}
        namespace: {{ .namespace }} 
        {{- else }}
        namespace: {{ .name }} 
        {{- end }}
      sources:
        - repourl: {{ .repourl }} 
          targetrevision: {{ .targetrevision }} 

          {{- if haskey . "chartpath" }}
          path: {{ .chartpath }}
          {{- end -}}

          {{- if haskey . "chartname" }}
          chart: {{ .chartname }} 
          {{- end -}}
          
          {{- if not (or (haskey . "chartpath") (haskey . "chartname")) }}
          chart: {{ .name }}
          {{- end }}

          {{- if haskey . "chartvalues" }}
          helm:
            valuefiles:
              - $values/applications/{{ .name }}/helm/values.yml
          {{- end -}}

        {{- if haskey . "chartvalues" }}
        - repourl: 'https://github.com/utilizable/charts'
          targetrevision: head
          ref: values
        {{- end -}}

        {{- if haskey . "manifests" }}
        - repourl: 'https://github.com/utilizable/charts'
          targetrevision: head
          path: applications/{{ .name }}/manifests/
        {{- end -}}
...
