#
# DES: ArgoCD apps of apps
# URL: 
#
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'infrastructure'
  namespace: 'argocd'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
    generators:
    - matrix:
      - list:
        elements:
        - file: infrastructure.yml
      generators:
         - git:
             repoURL: https://github.com/utilizable/charts
             revision: HEAD 
             files:
               - path: '{{ .file }}'
         - list:
             elementsYaml: "{{ .applications | toYaml }}"
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: 'default'
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    metadata:
      annotations:
        {{- if hasKey . "priority" }}
        argocd.argoproj.io/sync-wave: "{{ .priority }}"
        {{- end }}
    spec:
      destination:
        {{- if hasKey . "namespace" }}
        namespace: {{ .namespace }} 
        {{- else }}
        namespace: {{ .name }} 
        {{- end }}
      sources:
        - repoUrl: {{ .repoURL }} 
          targetRevision: {{ .targetRevision }} 

          {{- if hasKey . "chartPath" }}
          path: {{ .chartPath }}
          {{- end -}}

          {{- if hasKey . "chartName" }}
          chart: {{ .chartName }} 
          {{- end -}}
          
          {{- if not (or (hasKey . "chartPath") (hasKey . "chartName")) }}
          chart: {{ .name }}
          {{- end }}

          {{- if hasKey . "chartValues" }}
          helm:
            valueFiles:
              - $values/applications/{{ .name }}/helm/values.yml
          {{- end -}}

        {{- if hasKey . "chartValues" }}
        - repoURL: 'https://github.com/utilizable/charts'
          targetRevision: HEAD
          ref: values
        {{- end -}}

        {{- if hasKey . "manifests" }}
        - repoURL: 'https://github.com/utilizable/charts'
          targetRevision: HEAD
          path: applications/{{ .name }}/manifests/
        {{- end -}}
...
