#
# DES: ArgoCD apps of apps
# URL: 
#
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'generator'
  namespace: 'argocd'
  test:
    file: infrastructure.yml
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - key1: value1
          - matrix:
              generators:
                 - git:
                     repoURL: https://github.com/utilizable/charts
                     revision: HEAD 
                     files:
                       - path: "{{ .key1 }}"
                 - list:
                     elementsYaml: "{{ .applications | toYaml }}"
  template:
    metadata:
      name: 'dd'
    spec:
      project: 'default'
      destination:
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: 'https://github.com/utilizable/charts'
        targetRevision: HEAD
        path: applications/dd/manifests/
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
...
