global:
  env: development
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: development
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://github.com/ranrubin/argocd-app-of-apps
      targetRevision: HEAD

argocdApplications:
  helmGuestbook:
    disableAutomated: false
    disable: false
    name: helm-guestbook
    namespace: helm-guestbook
#    targetRevision: HEAD
    helm: true
