# Create custom definied storage-classes
storageClassConfigs: 

  storage-local-delete:
    storageClass:
      create: true
      defaultClass: false
      defaultVolumeType: hostPath
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
    sharedFileSystemPath: "/opt/storage-local-retain"
    ## OR
    # See above
    #nodePathMap:
    #  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    #    paths:
    #      - /opt/storage-local-retain

  storage-local-retain:
    storageClass:
      create: true
      defaultClass: false
      defaultVolumeType: hostPath
      reclaimPolicy: Retain 
      volumeBindingMode: WaitForFirstConsumer
    sharedFileSystemPath: "/opt/storage-local-retain"
    ## OR
    # See above
    #nodePathMap:
    #  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    #    paths:
    #      - /opt/storage-local-retain
