---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/NVIDIA/gpu-operator 
      chart: gpu-operator
      targetRevision: v24.6.0
      helm:
        values: |
          toolkit:
            env:
              - name: DOCKER_SOCKET
                value: /var/run/docker.sock
              - name: DOCKER_RUNTIME_CLASS
                value: nvidia
              - name: DOCKER_SET_AS_DEFAULT
                value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
