#
# DES: ArgoCD application definition for sealed-secrets
# REF: https://github.com/bitnami-labs/sealed-secrets
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
  - repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.16.1
    chart: sealed-secrets
    helm:
      values: |
        secretName: sealed-secrets-key
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    path: applications/sealed-secrets/manifests/          
#    helm:
#      valueFiles:
#        - $values/applications/sealed-secrets/helm/values.yaml
#  - repoURL: 'https://github.com/utilizable/charts'
#    targetRevision: HEAD
#    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
