#
# DES: ArgoCD application definition for sealed-secrets
# REF: https://github.com/bitnami-labs/sealed-secrets
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    path: democratic-csi/manifests/
  - repoURL: 'https://democratic-csi.github.io/charts/'
    chart: democratic-csi
    targetRevision: 0.14.6
    helm:
      valueFiles:
        - $values/democratic-csi/helm/values.yaml
  - repoURL: 'https://github.com/utilizable/charts'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
