#
# DES: csi storage for container orchestration systems 
# URL: 
#   https://github.com/democratic-csi/democratic-csi
#   https://github.com/fenio/k8s-truenas
#
---
csiDriver:
  name: "iscsi"
storageClasses:
- name: iscsi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
    detachedVolumesFromSnapshots: "false"
  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
driver:
  config:
    driver: freenas-api-iscsi

 # This config will be overwriten by secret   
    instance_id:
    httpConnection:
      protocol: http
      host: "hostname / ip"
      port: 80
      apiKey: "truenas api-key"
      allowInsecure: true    
    zfs:
      datasetParentName: "iscsi/dataset"
      detachedSnapshotsDatasetParentName: "iscsi/snapshot"
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize:
    iscsi:
      targetPortal: "hostname / ip"
      targetPortals: []
      interface:
      namePrefix: csi-
      nameSuffix: "-cluster"
      targetGroups:
        - targetGroupPortalGroup: 1 # obtained from truenas iscsi-share properties
          targetGroupInitiatorGroup: 3 # obtained from truenas iscsi-share properties
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
...
