additionalArguments:
  - "--api.dashboard=true"
  - "--log.level=debug"
  - "--providers.kubernetescrd"
  
  - "--entrypoints.web.address=:8000"
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  
  - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
  - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=ovh"
  - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
  - "--certificatesresolvers.myresolver.acme.email=konta@disroot.org"
  - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.myresolver.acme.storage=acme.json"
  
  - "--entrypoints.websecure.address=:8443"
  - "--entrypoints.websecure.http.tls=true"
  - "--entrypoints.websecure.http.tls.certResolver=myresolver"
  - "--entrypoints.websecure.http.tls.domains[0].main=anykey.pl"
  - "--entrypoints.websecure.http.tls.domains[0].sans=*.anykey.pl"

env:
  - name: OVH_ENDPOINT
    value: "ovh-eu"
  - name: OVH_APPLICATION_KEY
    valueFrom:
      secretKeyRef:
        name: ovh-secrets
        key: applicationKey
  - name: OVH_APPLICATION_SECRET
    valueFrom:
      secretKeyRef:
        name: ovh-secrets
        key: applicationSecret
  - name: OVH_CONSUMER_KEY
    valueFrom:
      secretKeyRef:
        name: ovh-secrets
        key: consumerKey

#ports:
#  web:
#    redirectTo: 
#      port: websecure
#  websecure:
#    tls:
#      enabled: true
#      certResolver: myresolver

#ingressRoute:
#  dashboard:
#    enabled: true
#    domain: "dashboard.anykey.pl"
