additionalArguments:
  - "--api.dashboard=true"
  - "--log.level=debug"
  - "--providers.kubernetescrd"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
  - "--certificatesresolvers.myresolver.acme.email=konta@disroot.org"
  - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.myresolver.acme.storage=acme.json"
  - "--entrypoints.websecure.address=:443"
  - "--entrypoints.websecure.http.tls=true"
  - "--entrypoints.websecure.http.tls.certResolver=myresolver"
  - "--entrypoints.websecure.http.tls.domains[0].main=anykey.pl"
  - "--entrypoints.websecure.http.tls.domains[0].sans=*.anykey.pl"

ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
      certResolver: myresolver

ingressRoute:
  dashboard:
    enabled: true
    domain: "dashboard.anykey.pl"
