#
# DES: csi storage for container orchestration systems 
# URL: 
#   https://github.com/democratic-csi/democratic-csi
#   https://github.com/fenio/k8s-truenas
#
---
csiDriver:
  name: "nfs"
storageClasses:
- name: nfs
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs
    detachedVolumesFromSnapshots: "false"
  mountOptions:
  - noatime
  - nfsvers=3
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
driver:
  # https://github.com/democratic-csi/charts/blob/b08d58f079d3ac812a75454c4d992f10c830af04/stable/democratic-csi/values.yaml#L21
  #existingConfigSecret: democratic-driver-config-nfs
  config:
#    driver:
#    instance_id:
#    httpConnection:
#      protocol: http
#      host: 192.168.1.5
#      port: 80
#      apiKey: 1-bIojIiah5Mckcc9Ma6YaIqbXVwJu7QT7sgQpgxiV4sorYtHMfAQWMxCbFKd0cilj
#      allowInsecure: true
#    zfs:
#      datasetParentName: lava/datalake
#      detachedSnapshotsDatasetParentName: laval/snaplake
#      datasetEnableQuotas: true
#      datasetEnableReservation: false
#      datasetPermissionsMode: "0777"
#      datasetPermissionsUser: 0
#      datasetPermissionsGroup: 0
#    nfs:
#      shareHost: 192.168.1.5
#      shareAlldirs: false
#      shareAllowedHosts: []
#      shareAllowedNetworks: []
#      shareMaprootUser: root
#      shareMaprootGroup: root
#      shareMapallUser: ""
#      shareMapallGroup: ""
...
