#
# DES: Sealed secret 
# URL: https://github.com/bitnami-labs/sealed-secrets
#
# HELM-REF:
#  https://github.com/democratic-csi/charts/blob/b08d58f079d3ac812a75454c4d992f10c830af04/stable/democratic-csi/templates/driver-config-secret.yaml#L1
#  https://github.com/democratic-csi/charts/blob/b08d58f079d3ac812a75454c4d992f10c830af04/stable/democratic-csi/templates/controller.yaml#L40
#
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: democratic-driver-config-nfs
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgByFi8z/LNcxuuuiERXyvCrN+jdYoMVfaz9NHy/ztdnbwx+OoFmEE+konkyLcZidclhY+MxiXdAysi7ijbIyW2qDU0hmvEaQFdXIoj5wG0zuDyIiXKqdnLAwwv4vsKSVBuDMOVmD7tJokO0u4+ZLePzeNTubbiHI/HH8V+2x/jYiQBwTLfxI3eJKM8BIRqKMl5RMtVix/2krOo+YBuUTeIka52jwSASjMO1nIINp95bEIaXN++rJUo4Tr2+WCnej7Squjf7si7HCqb1Nbybn1Q7Cn6BGUaFBfILkgMZUolOPSyyD2kICgNeCT6OZbWA+r0UZNeCMAEzWo0Sbhit0M7+dsls0t3xu6L4qGfQp/GZYWD1yNrB4PfHcnbmQKqfZKWAsfu0CLyGo/X/GN1fGiKPb/gRaMbaEpm5qJDd9MetQCG3uR8k5h0CXX5fB96yRsig5JzIFTF3RiU7HruJ8uioq7ZXhBfbvp5ry+ZnL6F5FphQwDeLAQgOqoKZnohmE11CtJlWuP3u5hhIKagKYrX87Cv/pjrP8XNmdpUxlsOAjV/NkTSFMgGNI57Dh8yEKsL/WwPvgFqKoLiUE3H+e/Y+5I5rqZtlqkkAkSiogRVJqZM266jLnlbPBGQhuBsoU7WCEf4koAQ718p0ObBYXOK01rEWqqumWNmCiuN5ZqLpWj8O3zQpLVVHc0IHkeTJrwvhYhFKbGBkgCcRi5ExxFaldtpGC6+g3tp6if1FeJOs69OhClD6V2nO9ZtFJzsbqtSVHrVWyZb16Yk21Iz8wTZ74s31qwtn06un2/RpR5h0kVsTbN+95QKIBe1+B1MuYz/gIGfD2zpS2wj+YpXLH3X0eP9PO5m19+SiWZ/kLjMnnuXEP1LEkNkEnmEBWgUmtmRs9pcTzegeAw+VlHDsduGI8fhVqH0Gi7x24ocORknis+ym6uL41yDSm/ocDU3Zp2N0+1ulw4ly7qb2jjvZ+WvNbMKRjHWOthYZ5SK1w+NFfKb2LC4/+ilOfgkTvLs6Lf+GL9eYbmHGl+mVuoUVL9uuDGSqWhHaBNKo3Tl6r+E9Cii+ief7rK+YOKQna9z4iKfgc2+qzjLt21WebyA0PO0IWg30QjRKcEMI0APLoYlW/cY5prYYTjtA/W0BU337Ako+1gKc/gVChmr8/FTYmuFPqa2dTDSWWwqE9rnMb1M53+szh/BnAvujAYtJ4OmRQAZoUMUc0CPUAb7G3rI+WQkDezOrzGL7gsdd137ojA4xah6B37+7tCcKkUZX7z0MekuWoMOfDyfZVqpghIshxxyO631ghVJ+/mXOTaCHSqTRJ+fKetSJ3BorgGJ8qXdVMmqScNry0h5vpaMzvWhbZin1n07qiyYD6tdip3qaggrkw//OqSXmqGJ6Feq25lYGHOilehsd2Wp56cmwrqWirYZIyGHBBOtz/7zRRZssY9orvSFO11ZzVilaXV+AAXVf/JqVTSTBEzOzmLHRSFEmJQgQYrDUx4FLAtwkExpIpG2M4KOZYwwbWZz2RSsteEmF2CB+kBvcJfYboAUvsBQ7Z/keulqi
  template:
    metadata:
      creationTimestamp: null
      name: democratic-driver-config-nfs
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: democratic-driver-config-iscsi
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgADhOpzKhJYDyAXx9/0LWdbTBwYF5XCB4o+MQH1SlterAzcZU5zsPf15XUveBCAsRk0xJBmPmjH8E0xH/bu2WXa1CNAtJrF860fBNq4tnyF4fet1cVtKNrqfO0t5a2ohsPWMLdpKQtuWu7ewiJUzON4vsYn/N+h2rhhbs4ZnN4sEQ8f6Ax7SrGyUV9J16BWa//BviW3M+goKlGuw+BnFFkBiRoTGCqLnuOW1jRYbAHNANSpmTs0PoP0NNFopGWM1Z3ILmCWrlJwwjDdY/yIvXkPq3knsCTeHP+x/ZoNCoHLvY7gh72dj05CsSU5kgDxTV2UjMXDc8I+6nJPwIPm0Ip1fMyDd832Bd273lAaI2KT4QzEgeZR5wBfyk4UXycXp9XIB7dM1Cf2uektHNohwps2/4aUE+IRD5VgFt9ksyEScOyAOHZ6kXLaN2dc3GR5OlkdzYLYAHN8eIuogpQ19kn09H9OCjOsI/8Eow+TzS/ZOvfD1c9DUO4i9BbkCsLZFZvp6bzcIvuXiCwNCTNPkS7zgwxPoDgv1WHkTMqwiYTK+Jm6SRCu3lysytfFUqLkyxMuGmkUxaPJdu6pfDussN5v1b0GZoaj/diuL7s+inH8YrZsNwOViXykOe/dBo8JWA1f2jk4u9WiDroiLQhP90kmBBn4k4j/d9ETYsodAqd40EwuUmx2TmOGFOxk2873HrfMH4VyB54Wxj0yl/683ZWyxWvmzQbxcTAHm45Mk3FAeA/F0S+vt1mxFyH5cACYAkOUkG6d5x+lJrn3Ks9d7Otvvg5FWJ+338BcrbW1zHcpiBUtKmKmHGKWKXBvx9UOemmKTptJXOnN9MyBUVByyPDtV2Y/vy2+TmwEhH6S3qAmoW4Hv5wtjPP6hTPinhxu63zOnO3fuctm6DQRqlGgcDpJ/u+Njcs5D4r1OBtLNwcTp2jBJQqLM2iuGQLGO6WXVeb+aT8NPvZNPN3BZEy1K+awz51k2zY5SxZEdwERzG6L4S9hv5+IsKnazvmKwdsM7eSMJdRAEsiF+GfEb0xWxPNoXdTJ+pLk53sxiUJNQhRLg2mcrM52juzkAzeFHqL5jvkF8K5wneyfMbrFf/9oPbCleUEFk1o1W4h61366sZSCRoebDaxVbXvDRkkzQO78cZhLBPxrDPX84mmIvILHB7bG3fWO356uGwxSoodB5TlH78Sq5JuAkOz0WkHVf5pKVXDp1os+Ek/d+tdmUTr63YvmJ8Cvd9GshPafRiMrR0QFGb54Wohh62q6zKr7Ba/eqTa0o+o0Bzv9OMpnyUYBhfct+0o7Jep2QxNG0XPzSYpfGUn+KgxqXKFGFny7xNFEy5WutSEjUiiYG1acFWCwuPkOnNsLKNFat8o4XSLxG2K1CSduv/vCmLxIlbWR5QEMm3tbP7MQFDfbdPBzb791KjaE2baOQcYIzpA59bThJh9oqP57SVV3/u1wlZsHyYM0UvsgChx1v6+9FB5WMQ52+HI8hCwQy0PfPCveKSTDIaF9VaxxZ4zDv8rQa9iEodBPX3AvJHJeIRRn/r10aMeWlGp2afm3yKKHCe2Dm26ptHMLzY6jBvAcwhsh+oers7AMivNCo7TFc2RjE5Wg0XdhS2Avhh6fkQ97DtUt5sWbloWUlEYpBad3jkoMJ1D9jEaC+TP/sQ/4tDJm79m2IGIQS3MGFE6qtMMRMx50Azec3rwatvXe8OA=
  template:
    metadata:
      creationTimestamp: null
      name: democratic-driver-config-iscsi
      namespace: democratic-csi
    type: Opaque
...
